USE [master]
GO

/****** Object:  Database [NHibernateDemo]    Script Date: 1/31/2021 2:56:54 PM ******/
CREATE DATABASE [NHibernateDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NHibernateDemo', FILENAME = N'/var/opt/mssql/data/NHibernateDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NHibernateDemo_log', FILENAME = N'/var/opt/mssql/data/NHibernateDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NHibernateDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NHibernateDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NHibernateDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NHibernateDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NHibernateDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NHibernateDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [NHibernateDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NHibernateDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NHibernateDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NHibernateDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NHibernateDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NHibernateDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NHibernateDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NHibernateDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NHibernateDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NHibernateDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NHibernateDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NHibernateDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NHibernateDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NHibernateDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NHibernateDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NHibernateDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NHibernateDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NHibernateDemo] SET RECOVERY FULL 
GO

ALTER DATABASE [NHibernateDemo] SET  MULTI_USER 
GO

ALTER DATABASE [NHibernateDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NHibernateDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NHibernateDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NHibernateDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NHibernateDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NHibernateDemo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NHibernateDemo] SET  READ_WRITE 
GO

-- Create Customer table:

USE [NHibernateDemo]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 1/31/2021 12:42:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[Id] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Create Order table:

USE [NHibernateDemo]
GO

/****** Object:  Table [dbo].[Order]    Script Date: 1/31/2021 12:43:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Order](
	[Id] [uniqueidentifier] NOT NULL,
	[Ordered] [datetime] NULL,
	[CustomerId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO

ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Customer]
GO




	



